# Generated by Django 5.0.1 on 2024-07-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("userid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=10)),
                ("points", models.IntegerField()),
                ("scrshot", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
