# Generated by Django 5.0.1 on 2024-07-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_appdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppProfile",
            fields=[
                ("appid", models.AutoField(primary_key=True, serialize=False)),
                ("appName", models.CharField(max_length=100)),
                ("appLink", models.CharField(max_length=100)),
                ("appCat", models.CharField(max_length=50)),
                ("appSubCat", models.CharField(max_length=50)),
                ("appIcon", models.ImageField(upload_to="icon/")),
            ],
        ),
        migrations.DeleteModel(
            name="AppDetail",
        ),
    ]
