# Generated by Django 5.0.1 on 2024-07-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_appprofile_delete_appdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppDetails",
            fields=[
                ("appid", models.AutoField(primary_key=True, serialize=False)),
                ("appName", models.CharField(max_length=100)),
                ("appLink", models.CharField(max_length=100)),
                ("appCat", models.CharField(max_length=50)),
                ("appSubCat", models.CharField(max_length=50)),
                ("appIcon", models.ImageField(upload_to="icon/")),
                ("points", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="AppProfile",
        ),
    ]
