# Generated by Django 5.0.1 on 2024-07-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_appdetails_delete_appprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="appdetails",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
