# Generated by Django 5.0.1 on 2024-07-17 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_appdetails_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appdetails",
            name="status",
        ),
        migrations.RemoveField(
            model_name="user",
            name="scrshot",
        ),
    ]
